alfio-event/alf.io

- src/main/java/alfio/config/MvcConfiguration.java
- src/main/java/alfio/controller/EventController.java
- src/main/java/alfio/controller/api/admin/LocationApiController.java
- src/main/java/alfio/model/modification/support/LocationDescriptor.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/webapp/resources/angular-templates/admin/partials/configuration/basic-settings.html
- src/main/webapp/resources/angular-templates/admin/partials/configuration/system.html
- src/main/webapp/resources/js/admin/feature/configuration/configuration.js
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
- src/main/webapp/resources/js/admin/service/service.js
- src/test/java/alfio/model/modification/support/LocationDescriptorTest.java
> implement #366, add here maps support

- README.md
because it rendered as #### instead of bold title on GitHub like it was
> fix README bad mark-up for "Running with multiple profiles"

- src/main/java/alfio/controller/ReservationController.java
- src/main/java/alfio/controller/api/admin/ConfigurationApiController.java
- src/main/java/alfio/controller/api/support/TicketHelper.java
- src/main/resources/alfio/db/HSQLDB/V22_1.15.1__FIX_EU_COUNTRIES_LIST.sql
- src/main/resources/alfio/db/MYSQL/V22_1.15.1__FIX_EU_COUNTRIES_LIST.sql
- src/main/resources/alfio/db/PGSQL/V22_1.15.1__FIX_EU_COUNTRIES_LIST.sql
- src/main/resources/alfio/i18n/public.properties
- src/main/resources/alfio/i18n/public_de.properties
- src/main/resources/alfio/i18n/public_fr.properties
- src/main/resources/alfio/i18n/public_it.properties
- src/main/resources/alfio/i18n/public_nl.properties
- src/main/webapp/WEB-INF/templates/event/reservation-page.ms
Implement #433 .
An additional PR will be done to add the possibility to "update" the vat nr.
> implement #433 

- src/main/resources/alfio/i18n/public_fr.properties
I only reviewed about the first half at this point, will finish if this gets merged.
> Fixed French errors

- README.md
- src/main/java/alfio/config/Initializer.java
- src/main/java/alfio/config/SpringBootInitializer.java
> remove anyway broken "http" (Spring Boot) profile (fixes #514)

- README.md
- docker-compose.yml
> Add Docker Compose support

- build.gradle
- gradle.properties
- src/main/java/alfio/config/Initializer.java
- src/main/java/alfio/config/MvcConfiguration.java
- src/main/java/alfio/config/SpringBootInitializer.java
- src/main/java/alfio/config/WebSecurityConfig.java
- src/main/java/alfio/controller/api/admin/UtilsApiController.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/Jobs.java
- src/main/java/alfio/manager/StripeCreditCardManager.java
- src/main/java/alfio/manager/system/Mailer.java
> Update spring 5.1

- docker-compose.yml
The links feature is [deprecated](https://docs.docker.com/compose/compose-file/#links), so we instead simply use ports and the fact that containers can see each other by hostname.
> Docker: remove dependency on links feature

- docs/deployment/OpenShift.md
mostly just because it was on https://alf.io/tutorials/openshift/ 
which I just removed via https://github.com/alfio-event/alf.io-website/pull/7
@cbellone
> add ElephantSQL to OpenShift doc

- .travis.yml
- gradle.properties
Currently, it seems that the coveralls plugin+gradle+jdk has some issues with tls1.3 and the currently used workaround stopped working.
Putting `systemProp.jdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" `
in the gradle.properties seems to do the trick.
> fix coveralls

- src/main/java/alfio/manager/WaitingQueueManager.java
or else this check will fail in the following scenario:
- 1 hidden category available
- 1 category available in the future
-> waiting list is enabled, but submitting will fail because the type is SOLD_OUT and does not match
> WaitingQueueManager.getSubscriptionType: ignore restricted categories

- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
ECJ complains about type mismatch:
`cannot convert from Optional<Object> to Optional<ResponseEntity<ValidatedResponse<String>>>`
> Added explicit cast to avoid type mismatch error

- src/main/resources/alfio/templates/invoice.ms
This commit fixed the issue with invoices with discounts. The invoice now shows the original ticket price instead of the already discounted price to be consistent with the reservation summary and receipts.
> Show correct ticket price on invoices #661

- src/main/java/alfio/manager/TicketReservationManager.java
Should be reported in the stable release too
> fix typo in releaseTicket -> ticket.getId() is used instead of the correct ticket.getCategoryId()

- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/EventStatisticsManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/WaitingQueueManager.java
- src/main/java/alfio/manager/system/DataMigrator.java
- src/main/java/alfio/repository/TicketCategoryRepository.java
- src/main/webapp/resources/angular-templates/admin/partials/event/detail.html
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/delete-category-modal.html
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
- src/main/webapp/resources/js/admin/service/service.js
- src/test/java/alfio/controller/api/v1/EventApiV1IntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
- src/test/java/alfio/manager/AdminReservationManagerIntegrationTest.java
- src/test/java/alfio/manager/EventManagerCategoriesTest.java
- src/test/java/alfio/manager/EventManagerIntegrationTest.java
- src/test/java/alfio/manager/TicketReservationManagerIntegrationTest.java
- src/test/java/alfio/manager/WaitingQueueManagerIntegrationTest.java
- src/test/java/alfio/manager/system/DataMigratorIntegrationTest.java
Added the ability to delete a ticket category from the UI.
Categories can be deleted if they do not contain pending or confirmed tickets.
fix #430
> #430 delete category from ui

- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/manager/EuVatChecker.java
- src/test/java/alfio/manager/EuVatCheckerTest.java
1. better handling when submitted country is null. Currently, the server return a 500 error if the user does not select a country.
2. better handling when the event organizer has not set the country of business. Currently it launch a 500 (null pointer exception) if the organizer has set to enable the reverse charge but has not set the country of business.
3. use the correct error message
> vat check fixes

- src/main/java/alfio/controller/api/admin/UtilsApiController.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/util/MustacheCustomTag.java
see #713 more coherence with the resulting preview from the admin.
> #713 always escape raw html in markdown description

- src/main/java/alfio/controller/api/admin/LocationApiController.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/modification/support/LocationDescriptor.java
- src/test/java/alfio/model/modification/support/LocationDescriptorTest.java
avoid creating useless data structure support for handling the geoapi. Use directly the results from  configurationManager.getFor
> refactor geoapi params, avoid one level of transformation

- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/system/Configuration.java
- src/main/java/alfio/repository/system/ConfigurationRepository.java
> rest api, get ticket categories: remove n+1 query when fetching ticket category configuration

- build.gradle
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/util/ObjectDiffUtil.java
- src/test/java/alfio/util/ObjectDiffTest.java
Work in progress.
Remove the java-object-diff library. We are only using for 2 cases, diffing objects with the same type and with only 1 level. 
We can do it with few lines of code and avoid some runtime warning (WARNING: Illegal reflective access by de.danielbechler.util.Classes)
> Remove java-object-diff

- src/main/java/alfio/controller/api/admin/AdditionalServiceApiController.java
- src/main/java/alfio/manager/CheckInManager.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/support/AdditionalServiceInfo.java
- src/main/java/alfio/manager/support/SuccessfulCheckIn.java
- src/main/java/alfio/model/FullTicketInfo.java
- src/main/java/alfio/model/Ticket.java
- src/main/java/alfio/model/TicketInfoContainer.java
- src/main/java/alfio/repository/TicketRepository.java
- src/test/java/alfio/manager/CheckInManagerIntegrationTest.java
We need to display additional items (e.g. T-Shirts) on the mobile app and check-in stations upon check-in, so that the operator can distribute them accordingly.
Given the current model limitations, we'll return the additional items only for the first ticket in the reservation.
> Include additional items in the check-in response

- src/main/java/alfio/controller/api/admin/AdditionalServiceApiController.java
- src/main/java/alfio/manager/CheckInManager.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/support/AdditionalServiceInfo.java
- src/main/java/alfio/manager/support/SuccessfulCheckIn.java
- src/main/java/alfio/model/FullTicketInfo.java
- src/main/java/alfio/model/Ticket.java
- src/main/java/alfio/model/TicketInfoContainer.java
- src/main/java/alfio/repository/TicketRepository.java
- src/test/java/alfio/manager/CheckInManagerIntegrationTest.java
We need to display additional items (e.g. T-Shirts) on the mobile app and check-in stations upon check-in, so that the operator can distribute them accordingly.
Given the current model limitations, we'll return the additional items only for the first ticket in the reservation.
this is a backport of #756
> Backport of #756

- src/main/java/alfio/manager/TicketReservationManager.java
- src/test/java/alfio/manager/TicketReservationManagerTest.java
If the reservation has been already confirmed by a payment provider
webhook, do not call the confirmation logic again
> Prevent confirmation email to be sent twice.

- src/main/java/alfio/controller/api/admin/EventApiController.java
include country code when exporting ticket data, and remove "creation" which is an internal information and sometimes is misleading for the organizer
> include country code when exporting ticket data

- README.md
Some gramatical error found in readme.md. So corrected those to help others get a better insight of the project.
> Typos and grammatical error in README.md removed

- .github/stale.yml
This PR adds the stale bot to handle old issues, by default it'll mark as stale every issue older than 365 days that hasn't been marked as enhancement, pinned or security. After another 14 days of inactivity it'll be automatically closed.
Before merging this PR the bot has to be enabled at project level by an administrator (https://github.com/apps/stale) and a "stale" label must be created.
> Add Stale Bot to handle old issues

- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/repository/TicketRepository.java
- src/main/resources/alfio/db/PGSQL/afterMigrate__003_VIEW_ticket_category_statistics.sql
- src/main/resources/alfio/db/PGSQL/afterMigrate__004_VIEW_events_statistics.sql
This fixes the "Schrödinger Tickets" problem:
This bug is triggered if all of the following conditions are met:
- display ticket left indicator is enabled, and
- all ticket categories are dynamic, and
- all ticket categories are expired
> hide count if there is no visible category available

- build.gradle
- src/main/java/alfio/config/SpringBootInitializer.java
- src/main/java/alfio/db/PGSQL/V22_1_14_8__MigrateMailchimp.java
- src/main/java/alfio/extension/ExtensionService.java
- src/main/java/alfio/manager/payment/PayPalManager.java
- src/main/java/alfio/manager/system/ConfigurationLevel.java
- src/main/java/alfio/manager/system/ConfigurationLevels.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/manager/system/ExternalConfiguration.java
- src/main/java/alfio/model/system/ConfigurationPathLevel.java
- src/main/java/alfio/repository/system/ConfigurationRepository.java
- src/test/java/alfio/manager/system/ConfigurationLevelTest.java
In some cases it can be useful to externalize:
- system configuration
- extensions
and not to save them to the database. 
This PR enables support for external configuration and extensions, which can be defined either:
- as JSON, using the [SPRING_APPLICATION_JSON](https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/html/boot-features-external-config.html)
- in the application.properties
> Add external config

- build.gradle
- src/main/java/alfio/config/DataSourceConfiguration.java
- src/main/java/alfio/db/PGSQL/V22_1_14_8__MigrateMailchimp.java
- src/main/java/alfio/extension/ScriptingExecutionService.java
- src/test/java/alfio/TestConfiguration.java
should do the trick for running the async extension scripts as sync one.
> run async scripts in a sync way in integration tests

- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
- src/test/resources/extension.js
In `ReservatioFlowIntegrationTest`, add an asynchronous extension to the database to enable detecting `RESERVATION_CONFIRMED` (an asynchronous event). We clear the extension_log table whenever we assert for presence of log. This PR also tests for `RESERVATION_CANCELLED`, `TICKET_ASSIGNED`, and `TICKET_CHECKED_IN`. Each time an event is logged, we expect to find exactly two logs for the event.
**Find all RESERVATION_CONFIRMED**
* There is only one `log(WARN) from script with event: RESERVATION_CONFIRMED` in the test output
> Detect Asynchronous Events + More

- src/main/java/alfio/controller/api/admin/FileUploadApiController.java
@syjer fix for some stupid mistake of #895
> fix wrong test of width with height

- README.md
This makes it much easier for people who don't have gradle and a jdk installed to build the container.
> Update Docker build steps

- src/main/java/alfio/controller/payment/SaferpayCallbackController.java
- src/main/java/alfio/controller/payment/api/saferpay/SaferpayPaymentWebhookController.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/payment/SaferpayManager.java
- src/main/java/alfio/manager/payment/saferpay/PaymentPageAssertRequestBuilder.java
- src/main/java/alfio/manager/payment/saferpay/PaymentPageInitializeRequestBuilder.java
- src/main/java/alfio/manager/payment/saferpay/RequestHeaderBuilder.java
- src/main/java/alfio/manager/payment/saferpay/TransactionCaptureRequestBuilder.java
- src/main/java/alfio/manager/payment/saferpay/TransactionInquireRequestBuilder.java
- src/main/java/alfio/manager/payment/saferpay/TransactionRefundBuilder.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/model/transaction/PaymentMethod.java
- src/main/java/alfio/model/transaction/PaymentProxy.java
- src/main/java/alfio/model/transaction/token/SaferpayToken.java
- src/main/java/alfio/model/transaction/webhook/EmptyWebhookPayload.java
- src/main/java/alfio/repository/TicketReservationRepository.java
- src/main/java/alfio/repository/TransactionRepository.java
- src/main/resources/alfio/i18n/public.properties
- src/main/webapp/resources/angular-templates/admin/partials/configuration/organization.html
- src/main/webapp/resources/angular-templates/admin/partials/configuration/system.html
- src/main/webapp/resources/js/admin/feature/configuration/configuration.js
- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.html
- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.js
- src/main/webapp/resources/js/admin/filter/util.js
- src/test/java/alfio/manager/payment/SaferpayManagerTest.java
- src/test/java/alfio/manager/payment/saferpay/PaymentPageAssertRequestBuilderTest.java
- src/test/java/alfio/manager/payment/saferpay/PaymentPageInitializeBuilderTest.java
- src/test/java/alfio/manager/payment/saferpay/RequestHeaderBuilderTest.java
- src/test/java/alfio/manager/payment/saferpay/TransactionCaptureRequestBuilderTest.java
- src/test/java/alfio/manager/payment/saferpay/TransactionRefundBuilderTest.java
> Saferpay integration

- src/main/java/alfio/controller/support/TemplateProcessor.java
- src/main/java/alfio/util/ImageUtil.java
Should avoid the creation of too many temporary files when calling Font.createFont.
> load deja vu sans font from cached file

- src/main/java/alfio/config/DataSourceConfiguration.java
- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/controller/form/ReservationCodeForm.java
- src/main/java/alfio/job/Jobs.java
- src/main/java/alfio/job/executor/AssignTicketToSubscriberJobExecutor.java
- src/main/java/alfio/manager/AdminReservationManager.java
- src/main/java/alfio/manager/AdminReservationRequestManager.java
- src/main/java/alfio/manager/PurchaseContextManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/system/AdminJobExecutor.java
- src/main/java/alfio/model/modification/AdminReservationModification.java
- src/main/java/alfio/model/subscription/AvailableSubscriptionsByEvent.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/repository/AdminReservationRequestRepository.java
- src/main/java/alfio/repository/SubscriptionRepository.java
- src/main/java/alfio/repository/TicketCategoryRepository.java
- src/main/java/alfio/repository/TicketRepository.java
- src/main/resources/alfio/db/PGSQL/V204_2.0.0.41__CREATE_INDEX_SUBSCRIPTIONS.sql
- src/main/resources/alfio/db/PGSQL/afterMigrate__000_VIEW_drops.sql
- src/main/resources/alfio/db/PGSQL/afterMigrate__015_VIEW_available_subscriptions_by_event.sql
- src/main/webapp/resources/angular-templates/admin/partials/configuration/system.html
- src/main/webapp/resources/js/admin/directive/admin-directive.js
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowWithSubscriptionIntegrationTest.java
- src/test/java/alfio/job/executor/AssignTicketToSubscriberJobExecutorIntegrationTest.java
- src/test/java/alfio/manager/AdminReservationManagerIntegrationTest.java
- src/test/java/alfio/test/util/IntegrationTestUtil.java
This new feature will enable organizers to generate and send tickets automatically to subscription owners for a given event.
The feature is not active by default and must be activated at system, organization or event level by enabling the following flag
**implementation note**
- Tickets are generated in a batch job, run every hour
- All active subscribers will get **one** ticket from the **first available category** . This might change in the future
> Generate tickets automatically for subscription owners

- .github/workflows/build-on-push.yml
- src/main/java/alfio/config/DataSourceConfiguration.java
- src/main/java/alfio/manager/EventNameManager.java
- src/main/java/alfio/manager/system/DataMigrator.java
- src/main/java/alfio/repository/EventAdminRepository.java
- src/main/java/alfio/repository/EventRepository.java
- src/test/java/alfio/BaseTestConfiguration.java
- src/test/java/alfio/config/DataSourceConfigurationTest.java
- src/test/java/alfio/manager/EventNameManagerIntegrationTest.java
- src/test/java/alfio/manager/EventNameManagerTest.java
- src/test/java/alfio/test/util/IntegrationTestUtil.java
- src/test/resources/init-db-user.sql
In the context of a multi-tenant alf.io instance, we need to bypass the Row Security Policy when checking if a given "event slug" has been already defined
> Fix duplicate slug check

- src/main/java/alfio/manager/PaymentManager.java
> when validating the payment provider for an event, don't filter out unconfigured ones

- src/main/java/alfio/controller/api/admin/PromoCodeDiscountApiController.java
- src/main/java/alfio/manager/PromoCodeRequestManager.java
- src/main/java/alfio/model/PromoCodeUsageResult.java
- src/main/java/alfio/repository/PromoCodeDiscountRepository.java
- src/main/resources/alfio/db/PGSQL/afterMigrate__000_VIEW_drops.sql
- src/main/resources/alfio/db/PGSQL/afterMigrate__016_VIEW_promocode_usage_details.sql
- src/main/webapp/resources/css/admin.css
- src/main/webapp/resources/js/admin/feature/promo-codes/list.html
- src/main/webapp/resources/js/admin/feature/promo-codes/promo-codes.js
- src/main/webapp/resources/js/admin/feature/promo-codes/usage-details.html
- src/main/webapp/resources/js/admin/service/service.js
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/DiscountedReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/HybridEventReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/OnlineEventReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowAuthenticatedUserIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowContext.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowWithSubscriptionIntegrationTest.java
This PR will introduce a new contextual view for promo codes.
Given a promo code which has already been used
organizers can see the details of the reservations made using that particular promo code by clicking on its name:
> Promo code usage details

- build.gradle
- src/main/java/alfio/controller/payment/api/stripe/StripePaymentWebhookController.java
- src/main/java/alfio/manager/payment/BaseStripeManager.java
- src/main/java/alfio/manager/payment/StripeCreditCardManager.java
- src/main/java/alfio/manager/payment/StripeWebhookPaymentManager.java
- src/main/java/alfio/util/HttpUtils.java
- src/test/java/alfio/BaseTestConfiguration.java
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowContext.java
- src/test/java/alfio/controller/api/v2/user/reservation/StripeReservationFlowIntegrationTest.java
- src/test/java/alfio/manager/payment/StripeWebhookPaymentManagerTest.java
- src/test/resources/transaction-json/stripe-success-valid-v2022-11-15.json
- src/test/resources/transaction-json/stripe-success-valid.json
Fix #1159 
- updated stripe API compatibility to 2022-11-15
- ensured that API requests with an older format are processed without problems
> #1159 stripe api compatibility

- src/main/java/alfio/controller/api/v1/admin/EventApiV1Controller.java
- src/main/java/alfio/manager/CheckInManager.java
- src/main/java/alfio/model/api/v1/admin/CheckInLogEntry.java
- src/main/java/alfio/model/audit/ScanAudit.java
- src/main/java/alfio/repository/audit/ScanAuditRepository.java
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowIntegrationTest.java
add an API to retrieve check-in log for a given event
> API to retrieve check-in log

- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/controller/api/v1/AttendeeApiController.java
- src/main/java/alfio/manager/AttendeeManager.java
- src/main/java/alfio/model/DetailedScanData.java
- src/main/java/alfio/model/SponsorScan.java
- src/main/java/alfio/repository/SponsorScanRepository.java
- src/main/resources/alfio/db/PGSQL/V204_2.0.0.49.5__SPONSOR_SCAN_OPERATOR.sql
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
During an event, it is possible that the same person gets scanned multiple times by different members of the sponsor staff.
The current strategy is to update the record to show data from the last scan. 
This has proven to be not very "user friendly" in different occasions.
This PR will add a "unique scan per operator" constraint, giving more flexibility to sponsors, and less opportunity to loose valuable data
> Manage multiple sponsors scan

- src/main/java/alfio/controller/OnlineCheckInController.java
- src/main/java/alfio/controller/api/v2/user/TicketApiV2Controller.java
- src/main/java/alfio/manager/CheckInManager.java
- src/main/java/alfio/manager/PassKitManager.java
- src/main/java/alfio/manager/wallet/GoogleWalletManager.java
- src/main/java/alfio/model/Event.java
- src/main/java/alfio/model/EventCheckInInfo.java
- src/main/java/alfio/model/Ticket.java
- src/main/java/alfio/model/checkin/CheckInFullInfo.java
- src/main/java/alfio/model/checkin/EventWithCheckInInfo.java
- src/main/java/alfio/util/EventUtil.java
- src/main/java/alfio/util/TemplateResource.java
- src/main/java/alfio/util/checkin/NameNormalizer.java
- src/main/java/alfio/util/checkin/TicketCheckInUtil.java
- src/main/resources/alfio/db/PGSQL/V205_2.0.0.50__QR_CASE_INSENSITIVE_MARKER.sql
- src/main/resources/alfio/db/PGSQL/afterMigrate__009_VIEW_checkin_ticket_event_and_category_info.sql
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/model/TicketTest.java
- src/test/java/alfio/test/util/IntegrationTestUtil.java
- src/test/java/alfio/util/EventUtilTest.java
- src/test/java/alfio/util/TemplateResourceTest.java
We should allow attendees to change case on their name (e.g. HOmer -> Homer) without causing troubles at the check-in.
This PR will generate case-insensitive QR Codes for events created with the new code.
> case insensitive qr code

- src/main/java/alfio/controller/api/v1/admin/ConfigurationApiV1Controller.java
- src/main/java/alfio/util/ItalianTaxIdValidator.java
- src/test/java/alfio/controller/api/v1/ConfigurationApiV1IntegrationTest.java
This allows external applications to set configuration options
Sponsored by [Eventplane](https://eventplane.it)
> Configuration API

- src/main/java/alfio/manager/support/CustomMessageManager.java
- src/main/webapp/resources/angular-templates/admin/partials/custom-message/index.html
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
Resolved the bug #1269 to show show correct {{eventName}} on compose message page
> #1269 Resolved the bug to show correct {{eventName}} on compose message page

- src/main/java/alfio/controller/api/v1/admin/EventApiV1Controller.java
- src/main/java/alfio/controller/api/v1/admin/SubscriptionApiV1Controller.java
- src/main/java/alfio/job/executor/AssignTicketToSubscriberJobExecutor.java
- src/main/java/alfio/manager/AccessService.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/SubscriptionManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/model/api/v1/admin/LinkedEvent.java
- src/main/java/alfio/model/api/v1/admin/LinkedSubscription.java
- src/main/java/alfio/model/subscription/AvailableSubscriptionsByEvent.java
- src/main/java/alfio/model/subscription/EventSubscriptionLink.java
- src/main/java/alfio/model/subscription/LinkEventsToSubscriptionRequest.java
- src/main/java/alfio/model/subscription/LinkSubscriptionsToEventRequest.java
- src/main/java/alfio/repository/EventRepository.java
- src/main/java/alfio/repository/SubscriptionRepository.java
- src/main/java/alfio/repository/TicketCategoryRepository.java
- src/main/java/alfio/repository/TicketRepository.java
- src/main/resources/alfio/db/PGSQL/V205_2.0.0.55__SUBSCRIPTION_LINKED_TO_CATEGORY.sql
- src/test/java/alfio/controller/api/v1/SubscriptionApiV1IntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowWithSubscriptionIntegrationTest.java
- src/test/java/alfio/job/executor/AssignTicketToSubscriberJobExecutorIntegrationTest.java
- src/test/java/alfio/manager/SubscriptionManagerIntegrationTest.java
- src/test/resources/api/descriptor.json
This feature will enable organizers to limit usage of a given subscription to specific ticket categories.
This will be initially possible only through API.
> Link subscriptions with categories

- src/main/java/alfio/manager/AdditionalServiceManager.java
- src/test/java/alfio/manager/AdditionalServiceManagerTest.java
Hi,
After updating my alf.io instance from `2.0-M4-2304` to `2.0-M4-2402-3` I noticed donation fields with user-defined pricing no longer work properly.
Here is an example of a ticket which costs $5.50 with an attached donation of $7.00:
When I reach the summary screen you can see the donation value in the table is $0.00:
Upon investigating I found this is being caused by the incorrect field being inserted into additional_service_item.src_price_cts. When the `event/{eventName}/reserve-tickets` endpoint is called, eventually we get to the 'AdditionalServiceManager.bookAdditionalServiceItems' method where we are inserting the additional_service_item rows to the database. For the src_price_cts column we are inserting as.getSrcPriceCts() which when the price is NOT fixed has a value of 0. …
> Fix user-defined donation prices being saved with zero value

- src/main/java/alfio/controller/api/admin/ResourceController.java
- src/main/java/alfio/controller/api/admin/UsersApiController.java
- src/main/java/alfio/controller/support/TemplateProcessor.java
- src/main/java/alfio/manager/FileBlobCacheManager.java
- src/main/java/alfio/manager/FileUploadManager.java
- src/main/java/alfio/manager/PassKitManager.java
- src/main/java/alfio/manager/system/BaseMailer.java
- src/main/java/alfio/repository/FileUploadRepository.java
- src/main/java/alfio/util/ImageUtil.java
- src/test/java/alfio/manager/system/BaseMailerTest.java
- src/test/java/alfio/util/ImageUtilTest.java
with a configurable "directory", used by file upload, font and images for passkit.
> add an unified "blob" cache

- src/main/java/alfio/config/MvcConfiguration.java
This allow to reduce the pression on the db, as each http request generate 3 select + 1 update to the session table from spring session jdbc.
We use a workaround explained in the following comment:  https://github.com/spring-projects/spring-session/issues/244#issuecomment-296605144
Reduction is interesting for the load event page case:
- from 9 request * (3  select + 1 update) = 27 select + 9 insert (index + 2 rest api call + 6 static resources)
- to 3 request * (3 select + 1 update ) = 9 select + 3 insert  (index + 2 rest api call)
To be noted, we will be able in a another PR to reduce the requests from 3 to 2 .
> Disable SessionRepositoryFilter when accessing static resources

- src/main/java/alfio/controller/FileController.java
- src/main/java/alfio/manager/FileBlobCacheManager.java
- src/main/java/alfio/manager/FileUploadManager.java
if we have the cached file and the user use if-none-match, we can bypass the db connection to fetch the metadata and return NOT_MODIFIED directly.
> Improve file handling with if-none-match

- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/test/java/alfio/controller/api/admin/EventApiControllerIntegrationTest.java
Supporting External Reference in List of Attendees Download
Closes #1422
> Supporting External Reference in List of Attendees Download

- src/main/java/alfio/controller/support/TemplateProcessor.java
- src/main/java/alfio/util/ImageUtil.java
By registering the default fonts, the user don't need to specify the family on the body.
This fix an issue in the receipt pdf.
> pdf: register default font for monospace,sans-serif,serif

- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/repository/TicketReservationRepository.java
- src/test/java/alfio/TestConfiguration.java
- src/test/java/alfio/controller/api/admin/EventApiControllerIntegrationTest.java
- src/test/java/alfio/test/toolkit/PromoCodeDiscountIntegrationTestingToolkit.java
Added voucher code in attendees data. https://github.com/alfio-event/alf.io/issues/1125
> Added voucher code
