alfio-event/alf.io

- src/main/java/alfio/model/modification/TicketCategoryWithStatistic.java
Please, accept this backport of "fix statistics"
> 1.3 maintenance

- src/main/resources/alfio/i18n/public_de.properties
Updated translation with SIE to DU, more concise expressions, general cleanup, fixing colons and added new translations for DE- Marked blocks
> Ajusted translation from SIE to DU, translated  new text blocks

- src/main/resources/alfio/i18n/public_de.properties
Shortening text because it does not match the button size and improved translation
> Improved translations

- src/main/java/alfio/config/WebSecurityConfig.java
- src/main/webapp/WEB-INF/templates/admin/index.ms
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
We added the logout functionality during this great Hackergarten. Please accept it!!
> #117 - Add logout functionality

- README.md
Add [lessons from mailing list discussion](https://groups.google.com/forum/#!topic/alfio/F6BPMOwsX48) to readme
> add note about install lombok plugin and autowired ide errors

- src/main/webapp/resources/angular-templates/admin/partials/configuration/setting.html
- src/main/webapp/resources/angular-templates/admin/partials/custom-message/index.html
- src/main/webapp/resources/angular-templates/admin/partials/event/detail.html
- src/main/webapp/resources/angular-templates/admin/partials/main/events.html
- src/main/webapp/resources/angular-templates/admin/partials/main/organizations.html
- src/main/webapp/resources/angular-templates/admin/partials/main/users.html
I only changed data-tooltip references and I think that also fixes tooltip popup deprecation too. I'm pretty sure everything still works (pretty simple changes).
> replace data-tooltip with data-uib-tooltip #138

- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-event-header.html
- src/main/webapp/resources/js/admin/directive/admin-directive.js
@syjer  please review and let me know if any changes required. Thanks.
> #128 upload file lime 1mb added

- src/main/webapp/resources/js/admin/ng-app/admin-application.js
small fix to enable a endDate parameter when creating a new category (fallback to now if no date specified)
> Calendar fix

- src/main/java/alfio/util/Validator.java
- src/main/webapp/WEB-INF/templates/event/attendee-fields.ms
- src/main/webapp/resources/angular-templates/admin/partials/event/detail.html
- src/main/webapp/resources/angular-templates/admin/partials/event/edit-event.html
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-field-modal.html
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
@syjer @cbellone  please have a look and let me know if any more changes required. Thanks.
> #153 optional/mandatory validation added for additional fields

- .travis.install-mysql-5.7.sh
- .travis.yml
> add mysql 5.7 in travis test matrix

- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/manager/EventStatisticsManager.java
- src/main/java/alfio/manager/WaitingQueueManager.java
- src/main/java/alfio/repository/EventDescriptionRepository.java
- src/main/java/alfio/repository/EventRepository.java
- src/main/java/alfio/repository/SpecialPriceRepository.java
- src/main/java/alfio/repository/TicketCategoryDescriptionRepository.java
- src/test/java/alfio/controller/ReservationFlowIntegrationTest.java
Still work in progress, but good enough to be merged in master: only a small part is broken now :)
> #318 remove last single event with statistics: WIP

- src/main/java/alfio/controller/api/support/EventListItem.java
(cherry picked from commit f8ea270)
> Fix the wrong URL attribute of an Event

- src/main/java/alfio/controller/api/ReservationApiController.java
- src/main/java/alfio/repository/TicketReservationRepository.java
- src/main/resources/alfio/i18n/public.properties
- src/main/resources/alfio/i18n/public_de.properties
- src/main/resources/alfio/i18n/public_fr.properties
- src/main/resources/alfio/i18n/public_it.properties
- src/main/resources/alfio/i18n/public_nl.properties
- src/main/webapp/WEB-INF/templates/event/reservation-page.ms
- src/main/webapp/resources/js/event/reservation-page.js
Add the possibility to reset the billing data.
> Add reset billing info

- src/main/java/alfio/controller/ReservationController.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
> implement #436 force ticket owner assignment at registration

- src/main/java/alfio/controller/api/admin/ResourceController.java
- src/main/java/alfio/model/ContentLanguage.java
- src/main/resources/alfio/templates/invoice.ms
- src/main/webapp/resources/angular-templates/admin/partials/configuration/organization.html
- src/main/webapp/resources/js/admin/feature/resources/edit/resources-edit.js
- src/main/webapp/resources/js/admin/feature/resources/show/resources-show.html
- src/main/webapp/resources/js/admin/feature/resources/show/resources-show.js
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
- src/main/webapp/resources/js/admin/service/resource-service.js
> #499 add organization level template editing

- README.md
- build.gradle
- src/main/java/alfio/config/Initializer.java
- src/main/java/alfio/config/JdbcSessionConfiguration.java
- src/main/java/alfio/config/MvcConfiguration.java
- src/main/java/alfio/config/SpringBootInitializer.java
- src/main/java/alfio/config/SpringBootLauncher.java
- src/main/java/alfio/config/WebSecurityConfig.java
- src/main/java/alfio/controller/api/support/CspReportApiController.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
remove 3 spring profiles: 
- jdbc-session
- debug-csp
- use-worker-name
> implement #544 refactor profiles

- src/main/webapp/resources/angular-templates/admin/partials/event/check-in.html
Simply added the same button than in "pending" tab.
>  #540 Add a button to display QR-CODE in checked-in tab

- src/main/java/alfio/controller/api/admin/AdminReservationApiController.java
- src/main/java/alfio/manager/AdminReservationManager.java
- src/main/java/alfio/manager/NotificationManager.java
- src/main/java/alfio/manager/SpecialPriceManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/WaitingQueueManager.java
- src/main/java/alfio/manager/WaitingQueueSubscriptionProcessor.java
- src/main/java/alfio/manager/support/CustomMessageManager.java
- src/main/java/alfio/repository/EmailMessageRepository.java
- src/main/resources/alfio/db/PGSQL/V201_2.0.0.4__ADD_RESERVATION_ID_IN_EMAILS.sql
- src/main/webapp/resources/js/admin/feature/reservation/reservation.service.js
- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.html
- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.js
- src/test/java/alfio/manager/SpecialPriceManagerTest.java
- src/test/java/alfio/manager/TicketReservationManagerTest.java
- src/test/java/alfio/manager/WaitingQueueManagerTest.java
- src/test/java/alfio/manager/WaitingQueueSubscriptionProcessorTest.java
Implement the show email log in reservation feature.
Note: it fix a double email confirmation sent bug. There is another open issue: see #585 .
> implement #541 add reservation emails log in reservation

- .gitignore
- docs/deployment/OpenShift.md
- etc/OpenShift/openshift.yaml
also (unrelated to #604) change vorburger/alf.io to alfio-event/alf.io (oups!)
and improve the OpenShift.md doc a little bit to hopefully be clearer
>  fix OpenShift YAML (fixes #604) 

- src/main/java/alfio/controller/EventController.java
- src/main/java/alfio/controller/api/admin/ResourceController.java
- src/main/java/alfio/extension/ScriptingExecutionService.java
- src/main/java/alfio/extension/SimpleHttpClient.java
- src/main/java/alfio/manager/FileUploadManager.java
- src/main/java/alfio/repository/FileUploadRepository.java
- src/main/java/alfio/repository/UploadedResourceRepository.java
Currently, we are holding a cache in memory for the uploaded data, we can move them on the file system
> move cache on tmp file

- src/main/java/alfio/controller/support/TemplateProcessor.java
- src/main/java/alfio/manager/FileUploadManager.java
Additionally, better handle the case when the temporary files are removed
> cache the deja vu sans mono as a temporary file

- src/main/java/alfio/config/DataSourceConfiguration.java
- src/main/java/alfio/job/Jobs.java
- src/main/java/alfio/job/executor/ReservationJobExecutor.java
- src/main/java/alfio/manager/system/AdminJobExecutor.java
- src/main/java/alfio/manager/system/AdminJobManager.java
- src/main/java/alfio/model/system/AdminJobSchedule.java
- src/main/java/alfio/repository/system/AdminJobQueueRepository.java
- src/main/resources/alfio/db/PGSQL/V202_2.0.0.8__ADMIN_JOB_QUEUE.sql
Initial implementation of admin job queue
> implement admin job queue

- build.gradle
- src/test/java/alfio/TestConfiguration.java
see #630. Should work better than the previous one!
> implement #630 switch to otj pg embedded

- README.md
> add links to hub.docker.com to README

- src/main/java/alfio/controller/api/admin/AdminWaitingQueueApiController.java
- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/util/ExportUtils.java
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/download-waiting-queue.html
- src/main/webapp/resources/angular-templates/admin/partials/main/sidebar.html
- src/main/webapp/resources/js/admin/directive/admin-directive.js
> implement #549 waiting queue export

- src/main/java/alfio/manager/PassKitManager.java
- src/main/java/alfio/model/modification/support/LocationDescriptor.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/util/Validator.java
- src/main/resources/alfio/db/PGSQL/V202_2.0.0.9__REMOVE_NOT_NULL_EVENT_LAT_LONG.sql
- src/main/webapp/WEB-INF/templates/event/show-event.ms
- src/main/webapp/resources/angular-templates/admin/partials/configuration/basic-settings.html
- src/main/webapp/resources/angular-templates/admin/partials/configuration/system.html
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-event-header.html
- src/main/webapp/resources/js/admin/service/service.js
- src/test/java/alfio/model/modification/support/LocationDescriptorTest.java
This pr enable alf.io to be used without google maps or HERE maps.
Implement #637 
Note: will need to check if a passbook can be made without a location.
> implement #637 remove map api key mandatory check

- src/main/java/alfio/controller/api/admin/ConfigurationApiController.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/webapp/resources/angular-templates/admin/partials/configuration/event.html
- src/main/webapp/resources/angular-templates/admin/partials/configuration/organization.html
- src/main/webapp/resources/angular-templates/admin/partials/configuration/setting.html
- src/main/webapp/resources/angular-templates/admin/partials/configuration/system.html
- src/main/webapp/resources/angular-templates/admin/partials/main/sidebar.html
- src/main/webapp/resources/css/admin.css
- src/main/webapp/resources/js/admin/directive/admin-directive.js
- src/main/webapp/resources/js/admin/feature/configuration/configuration.js
Small refactoring of settings UI
> Settings ui refactoring

- src/main/java/alfio/util/Validator.java
handle the case when the field is not present at all in the request.
> force required check if the submitted form does not contains the field

- build.gradle
- src/main/java/alfio/config/DataSourceConfiguration.java
- src/main/java/alfio/db/PGSQL/V22_1_14_8__MigrateMailchimp.java
to be merged after the release :)
> update npjt to 2.0.0

- src/main/java/alfio/config/WebSecurityConfig.java
- src/main/java/alfio/controller/EventController.java
- src/main/java/alfio/controller/ReservationController.java
- src/main/java/alfio/controller/api/v2/TranslationsApiController.java
- src/main/java/alfio/controller/api/v2/model/AdditionalService.java
- src/main/java/alfio/controller/api/v2/model/BasicEventInfo.java
- src/main/java/alfio/controller/api/v2/model/EventCode.java
- src/main/java/alfio/controller/api/v2/model/EventWithAdditionalInfo.java
- src/main/java/alfio/controller/api/v2/model/ItemsByCategory.java
- src/main/java/alfio/controller/api/v2/model/ReservationInfo.java
- src/main/java/alfio/controller/api/v2/model/TicketCategory.java
- src/main/java/alfio/controller/api/v2/model/ValidatedResponse.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/TicketApiV2Controller.java
- src/main/java/alfio/controller/decorator/SaleableTicketCategory.java
- src/main/java/alfio/controller/form/ReservationForm.java
- src/main/java/alfio/controller/support/Formatters.java
- src/main/java/alfio/controller/support/SessionUtil.java
- src/main/java/alfio/manager/RecaptchaService.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/repository/AdditionalServiceTextRepository.java
- src/main/java/alfio/repository/TicketCategoryDescriptionRepository.java
- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
note: it's not complete.
Another set of work will be done to remove the old controllers.
The frontend is available at https://github.com/alfio-event/alf.io-public-frontend .
It will integrated when the next step will be completed.
> implement #588 public rest api

- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/system/Configuration.java
- src/main/java/alfio/repository/system/ConfigurationRepository.java
- src/test/java/alfio/manager/ConfigurationManagerIntegrationTest.java
Implement #663 a bulk fetch for configuration values (up to event level).
The most important user (EventApiV2Controller) has been updated to the new api.
> Bulk fetch configuration, implement #663

- src/main/java/alfio/controller/api/v2/InfoApiController.java
- src/main/java/alfio/controller/api/v2/model/AlfioInfo.java
- src/main/java/alfio/controller/api/v2/model/AnalyticsConfiguration.java
- src/main/java/alfio/controller/api/v2/model/EventWithAdditionalInfo.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/util/TemplateResource.java
- src/main/resources/alfio/templates/google-analytics.ms
- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
> #657 re enable goog analytics

- gradle.properties
- src/main/java/alfio/config/MvcConfiguration.java
- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/controller/api/admin/ResourceController.java
- src/main/java/alfio/controller/api/support/TicketHelper.java
- src/main/java/alfio/controller/api/v2/TranslationsApiController.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/TicketApiV2Controller.java
- src/main/java/alfio/manager/AdminReservationManager.java
- src/main/java/alfio/manager/NotificationManager.java
- src/main/java/alfio/manager/PassKitManager.java
- src/main/java/alfio/manager/SpecialPriceManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/payment/PayPalManager.java
- src/main/java/alfio/manager/payment/PaymentSpecification.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/ContentLanguage.java
- src/main/java/alfio/model/WaitingQueueSubscription.java
- src/main/java/alfio/util/EventUtil.java
- src/main/java/alfio/util/LocaleUtil.java
- src/main/java/alfio/util/MustacheCustomTag.java
- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
remove locale handling by session + cleanup/removal of use of  RequestContextUtils.getLocale .
> #657 removal/cleanup of requestcontextutils.getlocale

- build.gradle
- gradle.properties
- src/main/java/alfio/util/MustacheCustomTag.java
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/event-header.html
- src/main/webapp/resources/css/admin.css
- src/main/webapp/resources/js/admin/directive/admin-directive.js
- src/main/webapp/resources/js/admin/feature/additional-service/additional-services.html
- src/main/webapp/resources/js/admin/feature/ticket-category/ticket-category-detail.html
> implement #677 add github flavored markdown table support

- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-category-modal.html
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-category.html
- src/main/webapp/resources/bower_components/bootstrap-daterangepicker/daterangepicker-bs3.css
- src/main/webapp/resources/bower_components/bootstrap-daterangepicker/daterangepicker.js
- src/main/webapp/resources/css/admin.css
- src/main/webapp/resources/js/admin/directive/admin-directive.js
- src/main/webapp/resources/js/admin/feature/ticket-category/ticket-category.js
This will improve the layout (and hopefully the UX) of the "add/edit ticket category"
> #690 improve edit category

- .travis.yml
add pgsql11 in the build matrix.
makes #629 obsolete.
> enable postgresql11 in travis

- src/main/java/alfio/controller/IndexController.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/model/FileBlobMetadata.java
- src/main/java/alfio/util/MustacheCustomTag.java
- src/main/java/alfio/util/RequestUtils.java
- src/main/resources/alfio/i18n/public.properties
- src/main/resources/alfio/web-templates/event-open-graph-page.html
- src/test/java/alfio/util/RequestUtilsTest.java
Note, we could potentially move the current template page as a customizable template, so the user could modify it.
> implement #708 opengraph improvements

- src/main/webapp/resources/angular-templates/admin/partials/event/edit-event.html
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-category.html
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-event-header-modal.html
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-event-header.html
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-prices.html
- src/main/webapp/resources/css/admin.css
- src/main/webapp/resources/js/admin/directive/admin-directive.js
- src/main/webapp/resources/js/admin/feature/configuration/configuration.js
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
> #694 improvements to create event page

- src/main/resources/alfio/i18n/public_de.properties
Fixed "date bei time - date bei time" to "date um time - date um time"
Fixed Ihnen to Sie in email-ticket-released.text
> Fixed german translation

- src/main/java/alfio/config/WebSecurityConfig.java
- src/main/java/alfio/controller/api/v2/model/EventWithAdditionalInfo.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/manager/EuVatChecker.java
- src/main/java/alfio/manager/i18n/MessageSourceManager.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/EventDescription.java
- src/main/java/alfio/model/user/Organization.java
- src/main/java/alfio/repository/EventDescriptionRepository.java
- src/main/java/alfio/repository/user/OrganizationRepository.java
Optimize the get event rest api call, as it's the most important one.
The goal is here is optimizing the queries (in term of round trip and the data loaded).
> misc optim for get event rest api call

- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/util/EventUtil.java
- src/test/java/alfio/util/EventUtilTest.java
avoid calling more than needed the event and configuration tables.
> optimize get ticket categories rest call

- gradle.properties
- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/model/TicketFieldConfiguration.java
- src/main/java/alfio/model/api/v1/admin/EventCreationRequest.java
- src/main/java/alfio/util/EventUtil.java
- src/main/java/alfio/util/Validator.java
- src/main/webapp/resources/js/admin/feature/event-data-to-collect/edit-field-modal.html
- src/main/webapp/resources/js/admin/feature/event-data-to-collect/event-data-to-collect.js
This PR add support for radio buttons and checkbox (for multiple choices) for the additional fields.
> fix #675 add radio and checkbox

- src/main/java/alfio/manager/NotificationManager.java
- src/main/java/alfio/repository/EmailMessageRepository.java
This should avoid bloating the `email_message` and avoid sending duplicate email in case of send ticket too.
> try to reuse email in email_message table in case of send ticket too

- build.gradle
- src/main/java/alfio/config/MvcConfiguration.java
- src/main/java/alfio/controller/IndexController.java
- src/main/resources/alfio/web-templates/admin-index.ms
- src/main/resources/alfio/web-templates/login.ms
re enable csp, use strict dynamic.
> fix #740 re enable csp

- src/main/webapp/resources/js/admin/directive/admin-directive.js
> admin: fix color for ticket category handling

- src/main/java/alfio/controller/api/AttendeeApiController.java
- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/manager/AttendeeManager.java
- src/main/java/alfio/model/DetailedScanData.java
- src/main/java/alfio/model/SponsorScan.java
- src/main/java/alfio/repository/SponsorScanRepository.java
- src/main/resources/alfio/db/PGSQL/V202_2.0.0.12.3__ADD_SPONSOR_SCAN_NOTES.sql
- src/test/java/alfio/controller/ReservationFlowIntegrationTest.java
add the ability for sponsors to write some comments about the scanned person, in order to remember what they talked about during the attendee's visit to their booth/stand
> Add sponsor comments

- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/controller/api/v1/AttendeeApiController.java
- src/main/java/alfio/manager/AttendeeManager.java
- src/main/java/alfio/model/DetailedScanData.java
- src/main/java/alfio/model/SponsorScan.java
- src/main/java/alfio/repository/SponsorScanRepository.java
- src/main/resources/alfio/db/PGSQL/V202_2.0.0.12.3__ADD_SPONSOR_SCAN_NOTES.sql
- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
add notes for sponsor scan
This way they can have more details about the collected lead
> add notes for sponsor scan

- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
override invoice requested in case of free reservation.
Handle the case of free reservation in case of invoice only
> override invoice requested in case of free reservation

- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/model/api/v1/admin/EventCreationRequest.java
- src/main/java/alfio/model/modification/EventModification.java
- src/main/resources/alfio/web-templates/admin-index.ms
- src/main/webapp/resources/angular-templates/admin/partials/event/edit-event.html
- src/main/webapp/resources/angular-templates/admin/partials/main/sidebar.html
- src/main/webapp/resources/js/admin/directive/admin-directive.js
- src/main/webapp/resources/js/admin/feature/additional-service/additional-service.js
- src/main/webapp/resources/js/admin/feature/copy-event/copy-event.html
- src/main/webapp/resources/js/admin/feature/copy-event/copy-event.js
- src/main/webapp/resources/js/admin/feature/event-data-to-collect/event-data-to-collect.html
- src/main/webapp/resources/js/admin/feature/event-data-to-collect/event-data-to-collect.js
- src/main/webapp/resources/js/admin/feature/ticket-category/ticket-category.js
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
- src/main/webapp/resources/js/admin/service/service.js
- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
Add copy event functionality.
It will copy the event + additional options/donations + additional fields (note: they can be selected/deselected).
All the dates will be adjusted using the selected range when copying. If you change it afterward, you will need to adjust them!
Fix issue #598 and  #230
> fix #598 #230 copy event

- src/main/java/alfio/controller/api/admin/EventApiController.java
include country code when exporting ticket data, and remove "creation" which is an internal information and sometimes is misleading for the organizer
> [M2] include country code when exporting ticket data

- src/main/java/alfio/repository/TicketFieldRepository.java
check divide by 0 in statistic.
> handle 0 case, fix #765

- src/main/java/alfio/controller/EventController.java
- src/main/java/alfio/repository/SpecialPriceRepository.java
this will be solved in M2, this is a temporary patch for M1
> temporary fix for a race condition when using categories' access codes

- src/main/java/alfio/controller/api/admin/AdminReservationApiController.java
- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/manager/AdminReservationManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/system/DataMigrator.java
- src/main/java/alfio/util/FileUtil.java
- src/test/java/alfio/manager/TicketReservationManagerTest.java
Change invoice name.
Now the format is 
`eventShortName-YYYY-MM-dd-HHmmss-documentNumber.pdf`
Fix #743
> fix #743 change invoice name

- src/main/java/alfio/manager/CheckInManager.java
- src/main/java/alfio/repository/TicketSearchRepository.java
- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.html
- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.js
- src/test/java/alfio/controller/ReservationFlowIntegrationTest.java
fix #784 
backoffice: add confirm button on reservation page
include category check-in strategy when generating encrypted payload
> M1 misc bugfixing

- src/main/java/alfio/repository/TicketSearchRepository.java
- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.html
- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.js
fix #784
backoffice: add confirm button on reservation page
> Fix #784 search by reservation

- src/main/java/alfio/controller/api/support/TicketHelper.java
- src/main/java/alfio/controller/api/v2/user/TicketApiV2Controller.java
- src/main/java/alfio/controller/support/TemplateProcessor.java
- src/main/java/alfio/manager/ExtensionManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/model/extension/CustomEmailText.java
- src/main/java/alfio/util/TemplateManager.java
- src/main/java/alfio/util/TemplateResource.java
- src/main/resources/alfio/templates/confirmation-email-txt.ms
- src/main/resources/alfio/templates/ticket-email-txt.ms
- src/test/java/alfio/util/TemplateResourceTest.java
add two new extension hooks:
- CONFIRMATION_MAIL_CUSTOM_TEXT
- TICKET_MAIL_CUSTOM_TEXT
this would allow to add an extension to write customized content in the reservation confirmation email and ticket email
> Custom text email

- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/repository/EventDeleterRepository.java
- src/main/java/alfio/repository/PromoCodeDiscountRepository.java
- src/main/java/alfio/repository/SpecialPriceRepository.java
- src/test/java/alfio/manager/TicketReservationManagerConcurrentTest.java
- src/test/java/alfio/manager/TicketReservationManagerIntegrationTest.java
- src/test/java/alfio/manager/TicketReservationManagerTest.java
serialize access to special_price table when trying to get tokens for an access code
> serialize access to special_price table

- src/main/java/alfio/controller/api/v2/model/BasicEventInfo.java
- src/main/java/alfio/controller/api/v2/model/DateValidity.java
- src/main/java/alfio/controller/api/v2/model/DatesWithTimeZoneOffset.java
- src/main/java/alfio/controller/api/v2/model/EventWithAdditionalInfo.java
- src/main/java/alfio/controller/api/v2/model/TicketInfo.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/TicketApiV2Controller.java
- src/main/java/alfio/controller/support/FormattedEventDates.java
- src/main/java/alfio/controller/support/Formatters.java
- src/main/java/alfio/model/Event.java
- src/main/resources/alfio/i18n/public.properties
- src/main/resources/alfio/i18n/public_it.properties
- add message for displaying a confirmation when the user wants to cancel a reservation
- add detailed information about start/end date/time, including the UTC offset
> Display timezone info + cancel confirmation

- src/main/java/alfio/controller/api/v2/model/DatesWithTimeZoneOffset.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/model/api/v1/admin/EventCreationRequest.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/test/java/alfio/manager/TicketReservationManagerIntegrationTest.java
- src/test/java/alfio/manager/TicketReservationManagerTest.java
- src/test/java/alfio/manager/WaitingQueueManagerIntegrationTest.java
- src/test/java/alfio/manager/system/DataMigratorIntegrationTest.java
- src/test/java/alfio/util/ActiveTravisProfileResolver.java
- partially implement #731 
- fix warnings
- remove redundant serializer in DatesWithTimeZoneOffset
> Misc fixes

- src/main/java/alfio/manager/PassKitManager.java
use ticket validity date also for Pass
> Fix pass date (#816)

- gradle.properties
- src/main/java/alfio/controller/api/v2/model/EventWithAdditionalInfo.java
- src/main/java/alfio/controller/api/v2/model/PaymentProxyWithParameters.java
- src/main/java/alfio/controller/api/v2/model/ReservationInfo.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/controller/form/ReservationForm.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/PassKitManager.java
- src/main/java/alfio/manager/PaymentManager.java
- src/main/java/alfio/manager/PromoCodeRequestManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/repository/EventDeleterRepository.java
- src/main/java/alfio/repository/PromoCodeDiscountRepository.java
- src/main/java/alfio/repository/SpecialPriceRepository.java
- src/main/java/alfio/repository/TicketRepository.java
- src/main/webapp/resources/angular-templates/admin/partials/configuration/category.html
- src/main/webapp/resources/angular-templates/admin/partials/configuration/system.html
- src/main/webapp/resources/js/admin/feature/configuration/configuration.js
- src/main/webapp/resources/js/admin/feature/configuration/payment-method-blacklist.html
- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
- src/test/java/alfio/manager/TicketReservationManagerConcurrentTest.java
- src/test/java/alfio/manager/TicketReservationManagerIntegrationTest.java
- src/test/java/alfio/manager/TicketReservationManagerTest.java
- porting m1 fixes
- implement payment method blacklist at category level
> M1 fixes + payment blacklist

- gradle.properties
- src/main/java/alfio/manager/ExtensionManager.java
- src/main/java/alfio/manager/PaymentManager.java
- src/main/java/alfio/manager/support/FeeCalculator.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/resources/alfio/db/PGSQL/V202_2.0.0.16__ADD_FIXED_AND_PERCENTAGE_FEES.sql
- src/main/resources/alfio/db/PGSQL/afterMigrate__006_VIEW_reservation_and_ticket_and_tx.sql
- src/test/java/alfio/manager/support/FeeCalculatorTest.java
- add a more fine-grained fees calculation for Platform mode
- do not include invalid transactions when exporting attendees' data
> Better fees calculation

- build.gradle
- src/main/java/alfio/config/SpringBootLauncher.java
- src/main/java/alfio/extension/ScriptingExecutionService.java
- src/main/java/alfio/extension/SimpleHttpClient.java
- src/main/java/alfio/extension/SimpleHttpClientCachedResponse.java
- src/main/java/alfio/extension/SimpleHttpClientResponse.java
- src/main/java/alfio/manager/FileDownloadManager.java
- src/main/java/alfio/manager/RecaptchaService.java
- src/main/java/alfio/manager/payment/MollieCreditCardManager.java
- src/main/java/alfio/manager/system/MailgunMailer.java
- src/main/java/alfio/manager/system/MailjetMailer.java
- src/main/java/alfio/util/HttpUtils.java
Removed `OkHttpClient` dependency completely
> removed OkHttp dependency

- website/content/en/_index.html
Go to alfio-event/alf.io instead of google
> Fix github button on website

- build.gradle
- src/main/java/alfio/config/DataSourceConfiguration.java
- src/main/java/alfio/db/PGSQL/V22_1_14_8__MigrateMailchimp.java
- src/main/java/alfio/extension/ExtensionService.java
- src/main/java/alfio/extension/ScriptingExecutionService.java
- src/main/java/alfio/extension/SimpleHttpClient.java
- src/main/java/alfio/extension/SimpleHttpClientResponse.java
- src/main/java/alfio/manager/FileDownloadManager.java
- src/main/java/alfio/manager/RecaptchaService.java
- src/main/java/alfio/manager/payment/MollieCreditCardManager.java
- src/main/java/alfio/manager/payment/RevolutBankTransferManager.java
- src/main/java/alfio/manager/system/DefaultMailer.java
- src/main/java/alfio/manager/system/MailgunMailer.java
- src/main/java/alfio/manager/system/MailjetMailer.java
- src/main/java/alfio/model/AdditionalService.java
- src/main/java/alfio/util/HttpUtils.java
- src/test/java/alfio/TestConfiguration.java
- src/test/java/alfio/extension/SimpleHttpClientIntegrationTest.java
- src/test/java/alfio/manager/FileDownloadManagerIntegrationTest.java
- src/test/java/alfio/manager/payment/RevolutBankTransferManagerTest.java
Contains various refactoring for the http client.
WIP.
check list/todo:
> Misc refactoring for http client

- src/main/webapp/resources/js/admin/directive/admin-directive.js
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
fix copy event bugs: set ticket category ordinal if copied event has all 0, display map on copy event
> fix copy event bugs: set ticket category ordinal if copied event has all 0, display map on copy event

- gradle.properties
- src/main/java/alfio/controller/IndexController.java
- src/main/java/alfio/controller/api/v2/InfoApiController.java
- src/main/java/alfio/controller/api/v2/TranslationsApiController.java
- src/main/java/alfio/manager/i18n/MessageSourceManager.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/test/java/alfio/controller/api/v2/user/ReservationFlowIntegrationTest.java
Inline some api call directly in the index.html template
> inline en bundle and application info

- gradle.properties
- src/main/java/alfio/controller/IndexController.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/support/EventLoader.java
- src/main/java/alfio/controller/support/Formatters.java
This improve loading perf, especially for mobile.
> Inline event in index.html if possible

- src/main/java/alfio/manager/support/CustomMessageManager.java
- src/main/webapp/resources/angular-templates/admin/partials/custom-message/index.html
> Exposes ticketID in custom email

- src/main/java/alfio/config/WebSecurityConfig.java
- src/main/java/alfio/manager/user/UserManager.java
- src/main/webapp/resources/js/admin/feature/user-edit-current/user-edit-current.html
- src/main/webapp/resources/js/admin/service/user.service.js
Also fixes the Cancel button in the Personal information panel.
Adds a rule that a user can't update it's own role.
Fixes #868 .
> Fix supervisor profile page (#868)

- src/main/java/alfio/manager/NotificationManager.java
- src/main/java/alfio/util/EventUtil.java
This PR improves the calendar invite sent in the ticket email. It adds some extra properties like the organizer, status, method and product ID.
> Improve calendar invite

- src/main/java/alfio/controller/IndexController.java
- src/main/java/alfio/controller/api/v2/model/EventWithAdditionalInfo.java
- src/main/java/alfio/controller/api/v2/user/support/EventLoader.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
as title... Still WIP, but I think on the server side we are good.
> add possibility to define globally and event level css

- website/content/en/docs/Getting started/Deployment/openshift.md
OpenShift has a capital `s` in it. :metal:
> Formatting for OpenShift

- src/main/webapp/resources/js/admin/feature/reservation/view/reservation-view.html
> change Refund input type from text to number

- build.gradle
- src/main/java/alfio/controller/api/admin/FileUploadApiController.java
- src/main/webapp/resources/angular-templates/admin/partials/event/fragment/edit-event-header.html
- src/main/webapp/resources/js/admin/directive/admin-directive.js
currently we are rendering the svg server side, but the used library  is quite limited.
We can do it client side on the browser.
WIP, but globally should work, need some tests.
> handle svg client side

- src/main/java/alfio/config/WebSecurityConfig.java
- src/main/java/alfio/config/support/auth/APIKeyAuthFilter.java
- src/main/java/alfio/config/support/auth/APITokenAuthentication.java
- src/main/java/alfio/config/support/auth/OpenIdAlfioAuthentication.java
- src/main/java/alfio/config/support/auth/OpenIdAlfioUser.java
- src/main/java/alfio/config/support/auth/OpenIdAuthenticationFilter.java
- src/main/java/alfio/config/support/auth/OpenIdAuthenticationProvider.java
- src/main/java/alfio/config/support/auth/OpenIdCallbackLoginFilter.java
- src/main/java/alfio/config/support/auth/RecaptchaLoginFilter.java
- src/main/java/alfio/config/support/auth/RequestTypeMatchers.java
- src/main/java/alfio/config/support/auth/UserCreatorBeforeLoginFilter.java
- src/main/java/alfio/config/support/auth/WrongAccountTypeException.java
- src/main/java/alfio/controller/IndexController.java
- src/main/java/alfio/manager/system/OpenIdAuthenticationManager.java
> refactor WebSecurityConfig

- src/main/java/alfio/extension/ConsoleLogger.java
- src/main/java/alfio/extension/ExtensionService.java
- src/main/java/alfio/extension/ExtensionUtils.java
- src/main/java/alfio/extension/JSON.java
- src/main/java/alfio/extension/ScriptingExecutionService.java
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/resources/extension.js
Implement console.log
Override JSON with our own serializer/deserializer
> Improve js support

- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/payment/MollieWebhookPaymentManager.java
- src/main/java/alfio/manager/payment/SaferpayManager.java
- src/main/java/alfio/manager/payment/StripeWebhookPaymentManager.java
- src/main/java/alfio/manager/system/ConfigurationLevel.java
- src/main/java/alfio/model/transaction/capabilities/WebhookHandler.java
- src/test/java/alfio/manager/payment/StripeWebhookPaymentManagerTest.java
- src/test/resources/transaction-json/stripe-success-metadata-missing.json
- src/test/resources/transaction-json/stripe-success-valid.json
> try to use the most sensible context when processing stripe webhooks

- src/main/java/alfio/controller/OnlineCheckInController.java
- src/main/java/alfio/manager/ExtensionManager.java
- src/main/java/alfio/model/checkin/OnlineCheckInFullInfo.java
- src/main/resources/alfio/db/PGSQL/afterMigrate__009_VIEW_checkin_ticket_event_and_category_info.sql
add ticket additional info to ONLINE_CHECK_IN_REDIRECT extension
> add additional info to checkin extension

- src/main/java/alfio/manager/support/PaymentResult.java
- src/main/java/alfio/model/ContentLanguage.java
- src/main/java/alfio/model/WaitingQueueSubscription.java
- src/main/java/alfio/model/modification/SendCodeModification.java
- src/main/java/alfio/model/modification/support/LocationDescriptor.java
- src/main/java/alfio/model/poll/Poll.java
- src/main/java/alfio/model/result/ValidationResult.java
- src/main/java/alfio/model/system/Configuration.java
continue work for removing lombok. See #1068
> Delombok tostring  / equal

- src/main/java/alfio/config/authentication/APITokenAuthWebSecurity.java
- src/main/java/alfio/config/authentication/AbstractFormBasedWebSecurity.java
- src/main/java/alfio/config/authentication/support/AuthenticationConstants.java
- src/main/java/alfio/controller/api/admin/SystemApiKeyApiController.java
- src/main/java/alfio/controller/api/v1/admin/OrganizationsApiV1Controller.java
- src/main/java/alfio/manager/OrganizationDeleter.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/manager/user/UserManager.java
- src/main/java/alfio/model/modification/OrganizationModification.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/repository/EventRepository.java
- src/main/java/alfio/repository/OrganizationDeleterRepository.java
- src/main/java/alfio/repository/user/join/UserOrganizationRepository.java
- src/main/java/alfio/util/RequestUtils.java
- src/main/webapp/resources/js/admin/feature/users/confirm-api-key-rotation.html
- src/main/webapp/resources/js/admin/feature/users/users.html
- src/main/webapp/resources/js/admin/feature/users/users.js
- src/main/webapp/resources/js/admin/service/user.service.js
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/HybridEventReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/OnlineEventReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowAuthenticatedUserIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowWithSubscriptionIntegrationTest.java
- src/test/java/alfio/manager/ConfigurationManagerIntegrationTest.java
> Implement Reservation API

- src/main/java/alfio/controller/api/admin/SubscriptionApiController.java
- src/main/java/alfio/controller/api/v1/admin/EventApiV1Controller.java
- src/main/java/alfio/controller/api/v1/admin/SubscriptionApiV1Controller.java
- src/main/java/alfio/job/executor/AssignTicketToSubscriberJobExecutor.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/SubscriptionManager.java
- src/main/java/alfio/model/api/v1/admin/SubscriptionDescriptorModificationRequest.java
- src/main/java/alfio/model/api/v1/admin/subscription/CustomPeriodTerm.java
- src/main/java/alfio/model/api/v1/admin/subscription/EntryBasedTerm.java
- src/main/java/alfio/model/api/v1/admin/subscription/StandardPeriodTerm.java
- src/main/java/alfio/model/api/v1/admin/subscription/SubscriptionTerm.java
- src/main/java/alfio/model/modification/SubscriptionDescriptorModification.java
- src/main/java/alfio/repository/EventRepository.java
- src/main/java/alfio/repository/SubscriptionRepository.java
- src/main/java/alfio/util/LocaleUtil.java
- src/main/resources/alfio/db/PGSQL/V205_2.0.0.49__ADD_SUBSCRIPTION_STATUS.sql
- src/main/resources/alfio/db/PGSQL/afterMigrate__012_VIEW_subscription_descriptor_statistics.sql
- src/test/java/alfio/controller/api/v1/EventApiV1IntegrationTest.java
- src/test/java/alfio/controller/api/v1/SubscriptionApiV1IntegrationTest.java
- src/test/java/alfio/manager/SubscriptionManagerIntegrationTest.java
> implement subscription api

- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/test/java/alfio/manager/ConfigurationManagerIntegrationTest.java
> do not fail when option is blank

- src/main/resources/alfio/db/PGSQL/afterMigrate__004_VIEW_events_statistics.sql
do a right outer join in event statistics view to handle the case of an event without ticket category (note, this is possible only if done by modifying directly the database), should handle #1103
> update event statistics view

- gradle.properties
- src/main/java/alfio/controller/api/v1/admin/ReservationApiV1Controller.java
- src/main/java/alfio/controller/api/v2/model/ApiPurchaseContext.java
- src/main/java/alfio/controller/api/v2/model/EmbeddingConfiguration.java
- src/main/java/alfio/controller/api/v2/model/EventWithAdditionalInfo.java
- src/main/java/alfio/controller/api/v2/model/ReservationInfo.java
- src/main/java/alfio/controller/api/v2/model/SubscriptionDescriptorWithAdditionalInfo.java
- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/SubscriptionsApiController.java
- src/main/java/alfio/controller/api/v2/user/support/EventLoader.java
- src/main/java/alfio/controller/api/v2/user/support/PurchaseContextInfoBuilder.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/model/ReservationMetadata.java
- src/main/java/alfio/model/api/v1/admin/ReservationConfiguration.java
- src/main/java/alfio/model/api/v1/admin/ReservationCreationRequest.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/repository/TicketReservationRepository.java
- src/main/resources/alfio/db/PGSQL/V204_2.0.0.49.1__ADD_RESERVATION_METADATA.sql
- src/main/webapp/resources/angular-templates/admin/partials/configuration/system.html
- src/test/java/alfio/controller/api/v1/ReservationApiV1ControllerTest.java
- Add option for sending notification via postMessage API when the reservation process is embedded
- Add metadata to reservation
> Embedded customization

- src/main/java/alfio/util/MustacheCustomTag.java
- src/test/java/alfio/util/MustacheCustomTagTest.java
a new PR will be done for the M4 branch.
> Restrict protocols in markdown link

- src/main/java/alfio/controller/form/ReservationCreate.java
- src/main/java/alfio/controller/form/ReservationForm.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/model/api/v1/admin/AttendeeData.java
- src/main/java/alfio/model/api/v1/admin/AttendeesByCategory.java
- src/main/java/alfio/model/api/v1/admin/ReservationCreationRequest.java
- src/main/java/alfio/model/modification/AttendeeData.java
- src/main/java/alfio/model/modification/ReservationRequest.java
- src/main/java/alfio/model/modification/TicketReservationModification.java
- src/main/java/alfio/repository/TicketRepository.java
- src/main/java/alfio/util/MiscUtils.java
- src/main/java/alfio/util/ReservationUtil.java
- src/test/java/alfio/controller/api/v1/ReservationApiV1ControllerTest.java
- src/test/java/alfio/manager/WaitingQueueManagerIntegrationTest.java
- src/test/java/alfio/model/modification/ReservationRequestTest.java
- src/test/java/alfio/util/MiscUtilsTest.java
add the possibility to initialize attendees' data when creating a reservation
> Reservation API: add attendees

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/alfio/config/authentication/APITokenAuthWebSecurity.java
- src/main/java/alfio/config/authentication/AbstractFormBasedWebSecurity.java
- src/main/java/alfio/config/authentication/OpenIdAdminWebSecurity.java
- src/main/java/alfio/manager/payment/StripeWebhookPaymentManager.java
- src/test/java/alfio/controller/api/CheckRestApiStability.java
- src/test/java/alfio/e2e/NormalFlowE2ETest.java
- src/test/resources/api/descriptor.json
Update spring boot to 2.7.7 and remove deprecated WebSecurityConfigurerAdapter(s)
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
> refactor mvc security

- src/main/java/alfio/controller/api/v1/admin/ReservationApiV1Controller.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/model/api/v1/admin/ReservationAPICreationRequest.java
- src/main/java/alfio/model/api/v1/admin/SubscriptionReservationCreationRequest.java
- src/main/java/alfio/model/api/v1/admin/TicketReservationCreationRequest.java
- src/main/java/alfio/model/metadata/SubscriptionMetadata.java
- src/main/java/alfio/repository/SubscriptionRepository.java
- src/main/resources/alfio/db/PGSQL/V204_2.0.0.49.2__ADD_SUBSCRIPTION_METADATA.sql
- src/test/java/alfio/controller/api/v1/ReservationApiV1ControllerTest.java
- src/test/java/alfio/controller/api/v1/SubscriptionApiV1IntegrationTest.java
Adds the possibility for initiating a Subscription reservation via API
> create Subscription reservation via API

- src/main/java/alfio/controller/api/admin/EventApiController.java
- src/main/java/alfio/controller/api/admin/ExportApiController.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/ExportManager.java
- src/main/java/alfio/model/PromoCodeUsageResult.java
- src/main/java/alfio/model/ReservationsByEvent.java
- src/main/java/alfio/model/support/EventBasicInfo.java
- src/main/java/alfio/model/support/ReservationInfo.java
- src/main/java/alfio/model/support/TicketInfo.java
- src/main/java/alfio/repository/EventRepository.java
- src/main/java/alfio/repository/ExportRepository.java
- src/main/java/alfio/util/ExportUtils.java
- src/main/resources/alfio/db/PGSQL/afterMigrate__016_VIEW_promocode_usage_details.sql
- src/main/resources/alfio/web-templates/admin-index.ms
- src/main/webapp/resources/js/admin/feature/export-reservations/export-reservations-button.html
- src/main/webapp/resources/js/admin/feature/export-reservations/export-reservations-form.html
- src/main/webapp/resources/js/admin/feature/export-reservations/export-reservations.js
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
- src/main/webapp/resources/js/admin/service/service.js
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/CustomTaxPolicyIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/DiscountedReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/HybridEventReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/OnlineEventReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowAuthenticatedUserIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowWithSubscriptionIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/StripeReservationFlowIntegrationTest.java
Export reservations done during a given interval.
The export will produce an "Excel" file with a sheet for each event
> implement reservation export

- gradle.properties
- src/main/java/alfio/controller/api/v2/model/TicketCategory.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/controller/api/v2/user/ReservationApiV2Controller.java
- src/main/java/alfio/manager/EventManager.java
- src/main/java/alfio/manager/ReverseChargeManager.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/PriceContainer.java
- src/main/java/alfio/model/metadata/AlfioMetadata.java
- src/main/java/alfio/model/modification/MetadataModification.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/repository/system/ConfigurationRepository.java
- src/main/java/alfio/util/ItalianTaxIdValidator.java
- src/main/webapp/resources/js/admin/ng-app/admin-application.js
- src/test/java/alfio/manager/ReverseChargeManagerIntegrationTest.java
- src/test/java/alfio/util/ItalianTaxIdValidatorTest.java
Adds a "ticket category" option to control whether to apply taxes to a specific category or not.
> remove vat for a specific category

- src/main/java/alfio/config/MvcConfiguration.java
- src/main/java/alfio/config/authentication/AbstractFormBasedWebSecurity.java
- src/main/java/alfio/config/authentication/FormBasedWebSecurity.java
- src/main/java/alfio/config/authentication/OpenIdAdminWebSecurity.java
- src/main/java/alfio/controller/api/admin/UsersApiController.java
- src/main/java/alfio/manager/user/UserManager.java
- src/test/java/alfio/TestConfiguration.java
This pr fix the missing removal of active session of disabled/deleted users.
> Fix spring-session <-> spring security integration + session removal on user deletion/disable

- src/main/java/alfio/util/ExportUtils.java
- src/main/resources/alfio/web-templates/admin-index.ms
- fix issue found by @yelprofessor : avoid binding for potentially user controlled input (username).
- fix issue found by @lujiefsi : csv export should escape cells that may be triggering the formula execution of excel: to be noted, I've tested with libreoffice, need to be checked with excel (which has the option during import execute the formula on import).
Note: to be ported in the master branch too.
> fix various findings

- src/main/java/alfio/util/ExportUtils.java
- src/main/resources/alfio/web-templates/admin-index.ms
see https://github.com/alfio-event/alf.io/pull/1200
> cherry-pick fix various finding from M4 to master

- src/test/java/alfio/e2e/NormalFlowE2ETest.java
looks like the element was not in the viewport, thus clicking generated a failure + avoid to bring up the integration test utilities
> fix ff failure in e2e test

- website/content/en/docs/Configuration/Payment/Mollie.md
Added a simple guide how to configure Mollie for use in Alf.io as payment method.
> Added docs for Mollie

- src/main/java/alfio/controller/api/v1/admin/ConfigurationApiV1Controller.java
- src/main/java/alfio/manager/payment/OnSiteManager.java
- src/main/java/alfio/manager/system/ConfigurationLevel.java
- src/main/java/alfio/manager/system/ConfigurationLevels.java
- src/main/java/alfio/manager/system/ConfigurationManager.java
- src/main/java/alfio/model/subscription/SubscriptionDescriptor.java
- src/main/java/alfio/model/system/Configuration.java
- src/main/java/alfio/model/system/ConfigurationKeys.java
- src/main/java/alfio/model/system/ConfigurationPathLevel.java
- src/main/java/alfio/repository/EventDeleterRepository.java
- src/main/java/alfio/repository/OrganizationDeleterRepository.java
- src/main/java/alfio/repository/system/ConfigurationRepository.java
- src/main/resources/alfio/db/PGSQL/V205_2.0.0.51__PURCHASE_CONTEXT_CONFIGURATION.sql
- src/test/java/alfio/controller/api/v1/ConfigurationApiV1IntegrationTest.java
- src/test/java/alfio/manager/ConfigurationManagerIntegrationTest.java
- src/test/java/alfio/manager/system/ConfigurationLevelTest.java
- src/test/java/alfio/manager/system/ConfigurationManagerTest.java
- src/test/resources/alfio/db/PGSQL/afterMigrate__999_VIEW_count_resources_organization_event.sql
allow configuration at "PurchaseContext" level (Event/SubscriptionDescriptor)
add API for subscription configuration
> Purchase context level config

- frontend/.npmrc
- frontend/package-lock.json
- frontend/projects/public/package-lock.json
add .npmrc for avoiding 401 issue with fontawesome
> fix package-lock

- src/main/java/alfio/repository/EventDeleterRepository.java
delete code imported from m4 stable branch.
Should fix issue #1320
> delete references for ticket field in legacy tables

- src/main/java/alfio/repository/EventDeleterRepository.java
> complete fix issue #1320

- frontend/projects/public/src/app/additional-service-form/additional-service-form.component.html
- frontend/projects/public/src/app/additional-service-form/additional-service-form.component.ts
- frontend/projects/public/src/app/model/reservation-info.ts
- src/main/java/alfio/controller/api/support/AdditionalServiceWithData.java
- src/main/java/alfio/manager/AdditionalServiceManager.java
- src/main/java/alfio/manager/support/AdditionalServiceHelper.java
- src/main/java/alfio/repository/AdditionalServiceRepository.java
- src/test/resources/api/descriptor.json
This pr do 2 actions:
- assign by default all donations to the first ticket
- expose the type of the additional options and hide in the ticket form the list of donations
> fix issue #1324, handle donations

- lombok.config
Added a lombok.config file to restrict the use of annotation.
Then one by one, they will restricted until lombok is no more used.
> restrict lombok annotation use, add config file

- build.gradle
- frontend/admin/.gitignore
- frontend/admin/README.md
- frontend/admin/package-lock.json
- frontend/admin/package.json
- frontend/admin/src/main.css
- frontend/admin/src/main.ts
- frontend/admin/src/new-element.ts
- frontend/admin/src/vite-env.d.ts
- frontend/admin/tsconfig.json
- frontend/admin/vite.config.js
- src/main/java/alfio/config/MvcConfiguration.java
- src/main/java/alfio/controller/AdminIndexController.java
- src/main/resources/alfio/web-templates/admin-index.ms
This PR add the initial integration for [lit](https://lit.dev/) for the admin frontend.
I'll also add some documentation in how to develop too.
> Initial integration of lit for admin

- frontend/admin/README.md
- frontend/admin/package-lock.json
- frontend/admin/package.json
Update frontend dep for new admin frontend
> update lit, add context and task package

- build.gradle
- src/main/java/alfio/controller/support/TemplateProcessor.java
this fork use pdfbox3, a small adjustment in the code was necessary.
> switch to the new friendly fork of openhtmltopdf

- frontend/projects/public/src/app/shared/user.service.ts
- src/main/java/alfio/controller/IndexController.java
inline the call `/api/v2/public/user/authentication-enabled` in our index page. This avoid a http rest call.
> preload auth enabled check

- src/main/java/alfio/controller/IndexController.java
- src/main/java/alfio/controller/api/v2/user/EventApiV2Controller.java
- src/main/java/alfio/controller/support/DataPreloaderManager.java
- src/main/java/alfio/manager/TicketCategoryAvailabilityManager.java
- src/main/java/alfio/util/EventUtil.java
- src/test/java/alfio/controller/IndexControllerTest.java
- src/test/java/alfio/controller/api/ControllerConfiguration.java
- src/test/java/alfio/util/EventUtilTest.java
move all logic in a single read only transaction + fusion 2 configuration call.
> refactor ticket category availability rest api + index controller

- build.gradle
- src/main/java/alfio/controller/IndexController.java
- src/main/java/alfio/job/Jobs.java
- src/main/java/alfio/manager/AdminReservationManager.java
- src/main/java/alfio/manager/EventReservationManager.java
- src/main/java/alfio/manager/ExtensionManager.java
- src/main/java/alfio/manager/SubscriptionManager.java
- src/main/java/alfio/manager/SubscriptionReservationManager.java
- src/main/java/alfio/manager/TicketReservationManager.java
- src/main/java/alfio/manager/wallet/GoogleWalletManager.java
- src/main/java/alfio/model/DescriptorIdAndReservationId.java
- src/main/java/alfio/model/system/command/CleanupReservations.java
- src/main/java/alfio/repository/SubscriptionRepository.java
- src/main/java/alfio/repository/TicketRepository.java
- src/test/java/alfio/manager/SubscriptionManagerIntegrationTest.java
- src/test/java/alfio/manager/SubscriptionReservationManagerIntegrationTest.java
- src/test/java/alfio/manager/TicketReservationManagerTest.java
- src/test/java/alfio/manager/TicketReservationManagerUnitTest.java
Fix issue when cancelling subscriptions + extracting cancellation logic into dedicated managers.
> Fix issue with subscription cancellation 

- src/main/java/alfio/controller/Constants.java
- src/main/java/alfio/controller/api/v1/admin/ReservationApiV1Controller.java
- src/main/java/alfio/controller/api/v2/user/TicketApiV2Controller.java
- src/main/java/alfio/model/modification/AttendeeData.java
- src/main/java/alfio/model/modification/AttendeeResources.java
- src/test/java/alfio/controller/api/v1/ReservationApiV1ControllerTest.java
- src/test/resources/api/descriptor.json
Add resource links to reservation details API
> Add resources links to reservation details API

- build.gradle
- src/main/java/alfio/extension/ScriptingExecutionService.java
- src/main/java/alfio/extension/support/SandboxContextFactory.java
- src/main/java/alfio/manager/ExtensionManager.java
- src/main/java/alfio/model/extension/AttendeeResourcesContainer.java
- src/main/java/alfio/model/modification/AttendeeResources.java
- src/test/java/alfio/controller/api/v2/user/reservation/BaseReservationFlowTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/CustomTaxPolicyIntegrationTest.java
- src/test/java/alfio/controller/api/v2/user/reservation/ReservationFlowTicketMetadataIntegrationTest.java
- src/test/resources/ticket-custom-metadata-extension.js
wrap record in a regular class to enable interop with Rhino + update Rhino to the latest version
> fix rhino record binding issue

- frontend/projects/public/src/app/additional-field/additional-field.component.ts
- frontend/projects/public/src/app/shared/invalid-feedback.directive.ts
it seems that having a dot in an additional info name cause issues. To be noted, we should not allow for new fields to have this kind of names
> better handling with form field name with dot

- src/main/webapp/alfio-admin-v1/js/admin/directive/admin-directive.js
Purple color is not proposed to selection for badge color.
> add purple color for badge color selection

- frontend/projects/public/src/app/event-display/event-display.component.ts
This is fix for uppercase in promocode for the visitor.
> Fix for #1437

- src/main/java/alfio/config/MvcConfiguration.java
- src/main/resources/public/robots.txt
some url we would like to not be indexed if possible.
> add robots.txt
